Repository SU-SWS/c_sharp_subtheme, pull requests merged in 2024-05, with the labels that each got.

#10 Simply facet refinements and states
  algolia-search/.yarn/install-state.gz
  algolia-search/package.json
  algolia-search/src/algolia-search.island.tsx
  algolia-search/src/facets.tsx
  algolia-search/src/search-form.tsx
  algolia-search/yarn.lock
Labels: size/l

#7 CSharp-48 - Facets for search (algolia)
  algolia-search/.env
  algolia-search/.gitignore
  algolia-search/.nvmrc
  algolia-search/.yarn/install-state.gz
  algolia-search/.yarnrc.yml
  algolia-search/dist/index.html
  algolia-search/dist/islands/algolia-search.island.js
  algolia-search/dist/islands/algolia-search.island.js.LICENSE.txt
  algolia-search/package.json
  algolia-search/src/algolia-search.island.tsx
  algolia-search/src/hits/default-hit.tsx
  algolia-search/src/hits/events.tsx
  algolia-search/src/hits/hit.types.tsx
  algolia-search/src/hits/news.tsx
  algolia-search/src/search-form.tsx
  algolia-search/src/template.html
  algolia-search/tsconfig.json
  algolia-search/webpack.config.js
  algolia-search/yarn.lock
  c_sharp_subtheme.info.yml
  package.json
Labels: size/xl

#11 CSHARP-55 | @jdwjdwjdw | Update Algolia filter and search results page
  algolia-search/dist/islands/algolia-search.island.js
  algolia-search/src/algolia-search.island.tsx
  algolia-search/src/search-form.tsx
  c_sharp_subtheme.theme
Labels: size/s

#12 CSHARP-000 | @jdwjdwjdw | Update Algolia filter sort, responsive fixup
  README.md
  algolia-search/dist/islands/algolia-search.island.js
  algolia-search/src/hits/default-hit.tsx
  algolia-search/src/search-form.tsx
  c_sharp_subtheme.info.yml
Labels: size/xs

#13 FIXUP - Adding hits per page configuration.
  CHANGELOG.md
  README.md
  algolia-search/dist/islands/algolia-search.island.js
  algolia-search/src/algolia-search.island.tsx
  algolia-search/yarn.lock
  c_sharp_subtheme.info.yml
Labels: size/xl
